For making test, I need to creat random metrics for CNN model. Let's do it hear. \
Let's do 500 metrics

In [2]:
#Download lib
import torch 
import pandas as pd
import numpy as np

In [22]:
#Creat function to make int columnes

def creat_column_int(col_name, low, high):
    a,b = 500,1   #dimension of the pytorch tensor to be generated

    col_name = torch.distributions.uniform.Uniform(low,high).sample([a,b]).int()

    return(col_name)

In [20]:
#Creat function to make float columnes

def creat_column_float(col_name, low, high):
    a,b = 500,1   #dimension of the pytorch tensor to be generated

    col_name = torch.distributions.uniform.Uniform(low,high).sample([a,b])

    return(col_name)

In [23]:
#first colunme will be count of layers from 5 to 15

leys = creat_column_int('leys', 5, 15)
#print tensor
print(leys)

tensor([[ 7],
        [ 6],
        [ 8],
        [ 7],
        [13],
        [ 6],
        [10],
        [13],
        [ 9],
        [11],
        [ 8],
        [ 7],
        [12],
        [13],
        [ 8],
        [12],
        [12],
        [ 8],
        [14],
        [14],
        [13],
        [ 9],
        [10],
        [ 7],
        [ 5],
        [ 7],
        [14],
        [10],
        [13],
        [ 6],
        [ 5],
        [13],
        [10],
        [14],
        [13],
        [14],
        [ 8],
        [ 7],
        [ 7],
        [10],
        [14],
        [ 6],
        [14],
        [10],
        [ 5],
        [12],
        [10],
        [ 5],
        [12],
        [ 5],
        [ 7],
        [11],
        [ 5],
        [ 9],
        [ 6],
        [ 8],
        [11],
        [ 8],
        [ 5],
        [14],
        [ 9],
        [11],
        [11],
        [13],
        [ 6],
        [ 5],
        [13],
        [ 8],
        [ 5],
        [ 9],
        [10],
      

In [24]:
#second columne will be size of kernel size from 2x2 as 2, to 5x5 as 5

ker = creat_column_int('ker', 2, 5)
#print tensor
print(ker)

tensor([[3],
        [3],
        [2],
        [2],
        [4],
        [3],
        [4],
        [2],
        [4],
        [4],
        [2],
        [2],
        [2],
        [2],
        [4],
        [2],
        [3],
        [2],
        [2],
        [3],
        [3],
        [4],
        [4],
        [2],
        [3],
        [3],
        [2],
        [4],
        [2],
        [4],
        [4],
        [4],
        [4],
        [3],
        [2],
        [4],
        [4],
        [3],
        [3],
        [2],
        [3],
        [3],
        [3],
        [2],
        [4],
        [2],
        [4],
        [4],
        [4],
        [4],
        [3],
        [2],
        [3],
        [4],
        [3],
        [3],
        [4],
        [4],
        [4],
        [4],
        [3],
        [4],
        [2],
        [4],
        [3],
        [4],
        [3],
        [2],
        [3],
        [4],
        [4],
        [2],
        [2],
        [3],
        [4],
        [3],
        [2],

In [25]:
#therd columne will be activation leyer - ReLU - 1, Softmax - 2 or Sigmoid - 3

act = creat_column_int('act', 1, 3)
#print tensor
print(act)

tensor([[1],
        [2],
        [2],
        [2],
        [1],
        [2],
        [1],
        [1],
        [2],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [1],
        [1],
        [1],
        [2],
        [2],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [1],
        [2],
        [1],
        [2],
        [1],
        [2],
        [1],
        [2],
        [1],
        [1],
        [2],
        [1],
        [1],
        [1],
        [2],
        [1],
        [2],
        [1],
        [1],
        [2],
        [1],
        [2],
        [1],
        [1],
        [1],
        [2],
        [1],
        [2],
        [2],
        [1],
        [1],
        [1],

In [26]:
#fourth columne will be using max pooling - 1 or avereg - 2 

pool = creat_column_int('pool', 1, 2)
#print tensor
print(pool)

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],

In [27]:
#and last colimne time of working CNN model, let's take it from 3 to 25 min

w_time = creat_column_float('w_time', 3, 25)
#print tensor
print(w_time)

tensor([[ 6.6231],
        [ 8.9196],
        [ 3.0394],
        [11.1242],
        [ 5.9903],
        [12.2712],
        [ 4.8395],
        [ 3.7103],
        [11.1193],
        [ 4.1779],
        [16.8089],
        [23.8024],
        [23.6804],
        [11.6889],
        [21.7238],
        [ 9.2619],
        [24.2384],
        [10.2512],
        [ 3.4839],
        [17.3271],
        [19.7390],
        [10.5384],
        [16.2928],
        [12.5593],
        [ 8.6109],
        [11.6519],
        [11.0254],
        [14.4849],
        [18.0876],
        [11.9401],
        [15.7359],
        [ 5.2553],
        [ 6.9678],
        [21.4169],
        [17.3861],
        [23.3071],
        [13.8936],
        [ 5.6152],
        [14.7238],
        [ 9.9839],
        [14.4054],
        [23.4153],
        [12.0663],
        [21.8991],
        [21.8865],
        [ 4.9744],
        [19.9664],
        [13.8791],
        [23.7630],
        [23.1255],
        [18.6938],
        [22.3449],
        [ 4.

In [28]:
#and now concat all tensers in one and upload it in csv file

CNN_mod = torch.cat((leys, ker, act, pool, w_time), -1)
print(CNN_mod)

tensor([[ 7.0000,  3.0000,  1.0000,  1.0000,  6.6231],
        [ 6.0000,  3.0000,  2.0000,  1.0000,  8.9196],
        [ 8.0000,  2.0000,  2.0000,  1.0000,  3.0394],
        ...,
        [ 6.0000,  2.0000,  1.0000,  1.0000,  5.0541],
        [11.0000,  2.0000,  2.0000,  1.0000, 21.9539],
        [ 9.0000,  2.0000,  1.0000,  1.0000, 16.5009]])


In [29]:
CNN_mod_np = CNN_mod.numpy()
CNN_mod_df = pd.DataFrame(data = CNN_mod_np, columns=['leys', 'ker', 'act', 'pool', 'w_time'])
CNN_mod_df.to_csv('CNN_mod.csv')