For making test, I need to creat rundom metrics for CNN model. Let's do it hear. \
Let's do 500 metrics

In [27]:
#Download lib
import torch 
import pandas as pd
import numpy as np

In [21]:
#first colunme will be count of layers from 5 to 15

a,b = 500,1   #dimension of the pytorch tensor to be generated
low,high = 5,15 #range of uniform distribution

leys = torch.distributions.uniform.Uniform(low,high).sample([a,b]).int()
#print tensor
print(leys)

tensor([[ 6],
        [ 8],
        [ 8],
        [ 9],
        [10],
        [14],
        [ 7],
        [ 6],
        [10],
        [ 9],
        [ 9],
        [11],
        [ 7],
        [ 5],
        [13],
        [10],
        [10],
        [11],
        [11],
        [11],
        [14],
        [14],
        [10],
        [12],
        [ 8],
        [ 9],
        [ 9],
        [ 7],
        [12],
        [10],
        [10],
        [ 6],
        [14],
        [ 8],
        [ 8],
        [ 5],
        [ 7],
        [ 8],
        [12],
        [14],
        [ 7],
        [14],
        [ 5],
        [ 9],
        [ 9],
        [13],
        [ 8],
        [12],
        [10],
        [ 7],
        [ 8],
        [ 7],
        [ 7],
        [10],
        [14],
        [14],
        [ 7],
        [ 5],
        [11],
        [12],
        [10],
        [12],
        [ 9],
        [13],
        [ 8],
        [ 8],
        [ 7],
        [ 9],
        [ 6],
        [13],
        [13],
      

In [22]:
#second columne will be size of kernel size from 2x2 as 2, to 5x5 as 5

low,high = 2,5 #range of uniform distribution

ker = torch.distributions.uniform.Uniform(low,high).sample([a,b]).int()
#print tensor
print(ker)

tensor([[4],
        [4],
        [2],
        [3],
        [3],
        [3],
        [2],
        [2],
        [4],
        [2],
        [2],
        [3],
        [2],
        [3],
        [4],
        [2],
        [3],
        [2],
        [2],
        [2],
        [2],
        [4],
        [4],
        [3],
        [2],
        [3],
        [4],
        [3],
        [3],
        [2],
        [2],
        [3],
        [2],
        [4],
        [3],
        [3],
        [2],
        [4],
        [4],
        [2],
        [4],
        [2],
        [2],
        [4],
        [3],
        [2],
        [3],
        [3],
        [3],
        [3],
        [2],
        [3],
        [3],
        [2],
        [4],
        [4],
        [4],
        [4],
        [3],
        [3],
        [4],
        [4],
        [3],
        [4],
        [4],
        [2],
        [2],
        [4],
        [4],
        [4],
        [3],
        [4],
        [3],
        [4],
        [4],
        [3],
        [3],

In [23]:
#therd columne will be activation leyer - ReLU - 1, Softmax - 2 or Sigmoid - 3

low,high = 1,3 #range of uniform distribution

act = torch.distributions.uniform.Uniform(low,high).sample([a,b]).int()
#print tensor
print(act)

tensor([[2],
        [1],
        [2],
        [1],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [1],
        [2],
        [1],
        [2],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [2],
        [2],
        [1],
        [2],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [1],
        [1],
        [2],
        [1],
        [2],
        [1],
        [1],
        [1],
        [2],
        [2],
        [1],
        [2],

In [24]:
#fourth columne will be using max pooling - 1 or avereg - 2 

low,high = 1,2 #range of uniform distribution

pool = torch.distributions.uniform.Uniform(low,high).sample([a,b]).int()
#print tensor
print(pool)

tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],

In [25]:
#and last colimne time of working CNN model, let's take it from 3 to 25 min

low,high = 3,25 #range of uniform distribution

w_time = torch.distributions.uniform.Uniform(low,high).sample([a,b])
#print tensor
print(w_time)

tensor([[21.1349],
        [ 4.9910],
        [ 3.8856],
        [10.0048],
        [ 7.4991],
        [20.2977],
        [20.8102],
        [13.8983],
        [ 5.4597],
        [23.2276],
        [15.4158],
        [23.8037],
        [15.7189],
        [ 5.9924],
        [19.2125],
        [18.7671],
        [ 3.9449],
        [12.5534],
        [11.1174],
        [10.4488],
        [18.3146],
        [19.9126],
        [12.0787],
        [15.1073],
        [23.9260],
        [11.7011],
        [ 6.7980],
        [ 3.7668],
        [ 5.2574],
        [ 6.2602],
        [ 5.9735],
        [22.8575],
        [20.5683],
        [ 7.0121],
        [ 3.5309],
        [20.1429],
        [10.7447],
        [13.3308],
        [ 8.5872],
        [ 8.3880],
        [ 8.7609],
        [ 6.9745],
        [17.8878],
        [ 4.4228],
        [22.6318],
        [ 4.2042],
        [10.4530],
        [13.7181],
        [10.2040],
        [17.0845],
        [19.7255],
        [ 3.3086],
        [10.

In [26]:
#and now concat all tensers in one and upload it in csv file

CNN_mod = torch.cat((leys, ker, act, pool, w_time), -1)
print(CNN_mod)

tensor([[ 6.0000,  4.0000,  2.0000,  1.0000, 21.1349],
        [ 8.0000,  4.0000,  1.0000,  1.0000,  4.9910],
        [ 8.0000,  2.0000,  2.0000,  1.0000,  3.8856],
        ...,
        [14.0000,  3.0000,  1.0000,  1.0000, 18.1889],
        [ 8.0000,  4.0000,  1.0000,  1.0000,  9.9484],
        [14.0000,  3.0000,  2.0000,  1.0000, 24.9067]])


In [29]:
CNN_mod_np = CNN_mod.numpy()
CNN_mod_df = pd.DataFrame(data = CNN_mod_np, columns=['leys', 'ker', 'act', 'pool', 'w_time'])
CNN_mod_df.to_csv('CNN_mod.csv')