For making test, I need to creat random metrics for CNN model. Let's do it hear. \
Let's do 500 metrics

In [1]:
#Download lib
import torch 
import pandas as pd
import numpy as np

In [2]:
#Creat function to make int columnes

def creat_column_int(col_name, low, high):
    a,b = 500,1   #dimension of the pytorch tensor to be generated

    col_name = torch.distributions.uniform.Uniform(low,high).sample([a,b]).int()

    return(col_name)

In [3]:
#first colunme will be count of layers from 5 to 15

leys = creat_column_int('leys', 5, 16)
#print tensor
print(leys)

tensor([[ 8],
        [14],
        [ 9],
        [13],
        [10],
        [13],
        [15],
        [10],
        [14],
        [ 5],
        [ 5],
        [ 6],
        [13],
        [10],
        [ 5],
        [ 5],
        [10],
        [13],
        [ 6],
        [12],
        [11],
        [12],
        [11],
        [ 5],
        [11],
        [10],
        [10],
        [10],
        [ 9],
        [ 9],
        [12],
        [ 8],
        [ 7],
        [ 7],
        [15],
        [12],
        [13],
        [12],
        [12],
        [ 8],
        [ 9],
        [ 7],
        [12],
        [ 8],
        [ 9],
        [ 7],
        [ 6],
        [ 7],
        [15],
        [ 8],
        [15],
        [15],
        [ 9],
        [11],
        [12],
        [ 7],
        [ 8],
        [ 8],
        [10],
        [ 6],
        [ 7],
        [10],
        [ 8],
        [15],
        [13],
        [ 7],
        [11],
        [15],
        [ 8],
        [15],
        [ 7],
      

In [4]:
#second columne will be size of kernel size from 2x2 as 2, to 5x5 as 5

ker = creat_column_int('ker', 2, 6)
#print tensor
print(ker)

tensor([[2],
        [2],
        [2],
        [4],
        [2],
        [3],
        [4],
        [2],
        [4],
        [2],
        [3],
        [3],
        [4],
        [5],
        [5],
        [4],
        [4],
        [4],
        [4],
        [2],
        [4],
        [2],
        [5],
        [4],
        [5],
        [4],
        [4],
        [4],
        [2],
        [5],
        [2],
        [3],
        [2],
        [5],
        [3],
        [5],
        [5],
        [3],
        [4],
        [5],
        [5],
        [2],
        [4],
        [2],
        [4],
        [5],
        [2],
        [5],
        [3],
        [2],
        [5],
        [3],
        [3],
        [3],
        [2],
        [3],
        [2],
        [2],
        [5],
        [4],
        [4],
        [4],
        [4],
        [3],
        [4],
        [2],
        [2],
        [5],
        [5],
        [4],
        [5],
        [2],
        [5],
        [3],
        [4],
        [3],
        [5],

In [5]:
#therd columne will be activation leyer - ReLU - 1, Softmax - 2 or Sigmoid - 3

act = creat_column_int('act', 1, 4)
#print tensor
print(act)

tensor([[1],
        [3],
        [3],
        [2],
        [2],
        [2],
        [3],
        [1],
        [2],
        [2],
        [3],
        [3],
        [2],
        [1],
        [1],
        [3],
        [1],
        [3],
        [1],
        [1],
        [1],
        [3],
        [1],
        [3],
        [2],
        [1],
        [2],
        [3],
        [3],
        [2],
        [1],
        [3],
        [2],
        [2],
        [3],
        [3],
        [3],
        [3],
        [1],
        [1],
        [3],
        [3],
        [3],
        [1],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [1],
        [2],
        [2],
        [3],
        [3],
        [1],
        [3],
        [3],
        [2],
        [3],
        [1],
        [3],
        [3],
        [2],
        [1],
        [1],
        [1],
        [2],
        [2],
        [3],
        [1],
        [1],
        [3],
        [3],
        [3],
        [1],
        [1],

In [6]:
#fourth columne will be using max pooling - 1 or avereg - 2 

pool = creat_column_int('pool', 1, 3)
#print tensor
print(pool)

tensor([[1],
        [2],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [1],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [1],
        [1],
        [2],
        [2],
        [1],
        [2],
        [1],
        [2],
        [2],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [1],
        [1],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [1],
        [1],
        [2],
        [1],
        [2],
        [2],
        [2],
        [2],
        [2],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [2],
        [1],
        [1],
        [2],

In [8]:
#and now concat all tensers in one and upload it in csv file

CNN_mod = torch.cat((leys, ker, act, pool), -1)
print(CNN_mod)

tensor([[ 8,  2,  1,  1],
        [14,  2,  3,  2],
        [ 9,  2,  3,  1],
        ...,
        [ 7,  3,  1,  2],
        [ 5,  3,  3,  2],
        [ 7,  2,  2,  1]], dtype=torch.int32)


In [9]:
CNN_mod_np = CNN_mod.numpy()
CNN_mod_df = pd.DataFrame(data = CNN_mod_np, columns=['leys', 'ker', 'act', 'pool'])

In [13]:
CNN_mod_df.sample(3)

leys  ker  act  pool
412    15    3    3     2
207     9    3    1     2
407     8    2    1     1

Let every leyer add 2.48 min to model runtimr, every ker - 3.97. Act and pool just add.

In [14]:
CNN_mod_df['r_time'] = CNN_mod_df['leys']*2.48 + CNN_mod_df['ker']*3.97 + CNN_mod_df['act'] + CNN_mod_df['pool']

In [15]:
CNN_mod_df.sample(3)

leys  ker  act  pool  r_time
316    15    4    2     1   56.08
157     8    2    2     1   30.78
338    10    3    1     2   39.71

In [16]:
CNN_mod_df.to_csv('CNN_mod.csv')